#!/usr/bin/bash

if [ $# -eq 0 ]; then
	gcc -ffreestanding -c *.c -o out.o

	ld -o out.bin -Ttext 0x0 --oformat binary out.o
	#    -Ttext 0x0 works same as org it allows us to tell the compiler to set an offset 
	#       label address in our code to their absolute address in memory

	ndisasm -b 32 out.bin > out.dis
	#	 -b 32 tells the disassembler to decode to 32 bit assembly instruction
else
	gcc -ffreestanding -c $1 -o out.o

	ld -o out.bin -Ttext 0x0 --oformat binary out.o
	#    -Ttext 0x0 works same as org it allows us to tell the compiler to set an offset 
	#       label address in our code to their absolute address in memory

	ndisasm -b 32 out.bin > out.dis
	#	 -b 32 tells the disassembler to decode to 32 bit assembly instruction
fi
