;
;   The compiled kernel.c file is not guranteed to generate main function
;   as the entry point so we write this file which call main function
;   by linking object file generated by this file and kernel.c
;

; Ensures that we directly jump to kernel main function

[bits 32]       ; We're in protected mode by now
[extern main]   ; Declare that we'll be referencing external symbol 'main'
                ; so the linker can substitute the final address

call main       ; invoke main() in our C kernel
jmp $           ; Hang forever when we return from kernel